### ISSUE TITLE
stream urls seem dead.

### ISSUE THREAD

**Issue by mndrwd** [bosel/plugin.video.nederland24#27]
Plugin doesn't currently seem to provide functionality.

**Comment by marvinstorage** [comment]
Plugin ddoes not wwork:
`09:20:45.900 T:140219181418240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 238, in <module>
                                                playVideo(url)
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 198, in playVideo
                                                videopre = re.search(r'(http:.*?)\"', page).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
09:20:45.937 T:140220222269824   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_3FM_300881&mode=playVideo]
09:20:50.184 T:140219735283456   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 418
09:20:50.184 T:140219735283456   ERROR: CCurlFile::Open failed with code 418 for http://www.nieuws.nl/rss/algemeen
09:20:50.184 T:140219735283456   ERROR: Unable to obtain rss feed: http://www.nieuws.nl/rss/algemeen
09:20:50.687 T:140219173025536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 238, in <module>
                                                playVideo(url)
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 198, in playVideo
                                                videopre = re.search(r'(http:.*?)\"', page).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
09:20:50.734 T:140220222269824   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_3FM_300881&mode=playVideo]
09:20:54.405 T:140219181418240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 238, in <module>
                                                playVideo(url)
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 198, in playVideo
                                                videopre = re.search(r'(http:.*?)\"', page).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
09:20:54.467 T:140220222269824   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_NEDERLAND3_221687&mode=playVideo]
09:20:56.714 T:140219206596352   ERROR: Unable to find plugin
09:20:56.714 T:140220222269824   ERROR: GetDirectory - Error getting plugin://
09:20:56.718 T:140220222269824   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
09:21:47.623 T:140219181418240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 238, in <module>
                                                playVideo(url)
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 198, in playVideo
                                                videopre = re.search(r'(http:.*?)\"', page).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
09:21:47.672 T:140220222269824   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_3FM_300881&mode=playVideo]
09:24:37.409 T:140219198203648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 240, in <module>
                                                playVideo(url)
                                              File "/home/scrape/.kodi/addons/plugin.video.nederland24/nederland24.py", line 200, in playVideo
                                                videopre = re.search(r'(http:.*?)\"', page).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
09:24:37.456 T:140220222269824   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_3FM_300881&mode=playVideo]
`

**Comment by Rinse303** [comment]
Indeed, since the latest update this does not work anymore..  I cannot figure out what the issue is

**Comment by sphaero** [comment]
I can confirm, streams are not working anymore

**Comment by bosel** [comment]
Thanks for reporting, should be fixed now

**Comment by drpetje** [comment]
Not working for me, cant see a new version?

**Comment by nsteur** [comment]
Is there any information if the addon will be fixed again because here its also not working :(

**Comment by dmaxxximus** [comment]
this is still an issue, plugin worked for a while after last update but suddenly stopped working.
One of the errors, dunno if its of any help:
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nederland24/?url=LI_NEDERLAND1_221673&mode=playVideo]

**Comment by plusjoost** [comment]
Problem not solved on this side. installing mrarends' fix again.
